// <auto-generated />
namespace MrSimonAcademy2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RegisterModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegisterModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202006061113418_RegisterModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
